/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.template;

import java.net.URL;
import javafx.stage.Stage; //added
import java.util.HashMap;
import java.util.Map;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
// Blackjack imports and fields
import javafx.stage.Stage; //added
import javafx.scene.control.Button;  //added
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;  //added
import java.util.ArrayList; //added
import java.util.List;  //added
import javafx.scene.control.Button; //added



public class App extends Application
{
    private VBox root;
    private StackPane table;
    private int width = 800;
    private int height = 600;

    // Blackjack game state and UI controls
private List<Card> playerHand = new ArrayList<>();
private List<Card> dealerHand = new ArrayList<>();
private Deck deck;

private Button hitButton = new Button("Hit");
private Button standButton = new Button("Stand");
private Button newGameButton = new Button("New Game");
private HBox controlButtons = new HBox(10, hitButton, standButton, newGameButton);
private Button restartButton = new Button("Restart Game");


// Betting and status display
private int playerMoney = 100;
private int currentBet = 0;

private Label moneyLabel = new Label("Money: $100");
private Label resultLabel = new Label(""); // shows win/loss message
private TextField betInput = new TextField(); // input for bet
private Button placeBetButton = new Button("Place Bet");

private HBox bettingControls = new HBox(10, new Label("Bet: $"), betInput, placeBetButton);




    @Override
    public void start(Stage primaryStage) throws Exception
    {
        root = new VBox();

        // menubar
        root.getChildren().add(createMenuBar());

        // mouse handler
        //addMouseHandler();

        table = new StackPane();
        root.getChildren().add(table);

        // don't give a width or height to the scene
        //Scene scene = new Scene(root);
        Scene scene = new Scene(root, width, height);

        URL styleURL = getClass().getResource("/style.css");
        String stylesheet = styleURL.toExternalForm();
        scene.getStylesheets().add(stylesheet);
        primaryStage.setTitle("Play Poker like it's 2004");
        primaryStage.setScene(scene);
        primaryStage.show();
        // Set up Blackjack buttons and logic
        setupBlackjackUI();

        


        primaryStage.setOnCloseRequest(event -> {
            System.out.println("oncloserequest");
        });

        //System.out.printf("center of stackpane  %f, %f\n", table.getWidth() / 2, table.getHeight() / 2);

    }

    // private void addMouseHandler()
    // {
    //    root.setOnMouseClicked(event -> {
    //        deal();
    //   });
    //}

    private void clearTable()
    {
        table.getChildren().removeIf(node -> node instanceof ImageView);
    }

    //private void deal()
    //{
    //    clearTable();
    //    Deck d = new Deck();
    //    d.shuffle();
    //    for (int i = 1; i <=7; i++)
    //    {
    //        Card card = d.draw();
    //        placeCard(card, i);
    //    }
    //    placeCard(null, 8);
    //    placeCard(null, 9);
    //}

    private MenuBar createMenuBar()
    {
        MenuBar menuBar = new MenuBar();
    	menuBar.getStyleClass().add("menubar");

        //
        // File Menu
        //
    	Menu fileMenu = new Menu("File");

        addMenuItem(fileMenu, "Load from file", () -> {
            System.out.println("Load from file");
        });

        menuBar.getMenus().add(fileMenu);

        return menuBar;
    }

    private static Map<Card, ImageView> cardImageViews = new HashMap<>();

    private static ImageView getBackOfCard()
    {
        // we need a new one every time
        return new ImageView(new Image(App.class.getResource("/assets/Back.png").toExternalForm()));
    }

    private static ImageView getCardImageView(Card card)
    {
        if (card == null)
        {
            return getBackOfCard();
        }
        if (!cardImageViews.containsKey(card))
        {
            String cardName = card.toString();
            String cardPath = "/assets/" + cardName + ".png";
            System.out.println("cardPath: " + cardPath);
            URL cardURL = App.class.getResource(cardPath);
            Image cardImage = new Image(cardURL.toExternalForm());
            ImageView cardImageView = new ImageView(cardImage);
            cardImageViews.put(card, cardImageView);
        }
        return cardImageViews.get(card);
    }

    private void placeCard(Card card, int number)
    {
        /*
         * The xOffset and yOffset are in terms of where the card should be placed
         * By default a StackPane will center the card at W/2, 0, so the center of the top
         * 1,2,3 are the flop
         * 4 is the turn
         * 5 is the river
         * 6 is the player's first card
         * 7 is the player's second card
         * 8 is the opponent's first card
         * 9 is the opponent's second card
         */
        int xOffset = 0;
        int yOffset = 0;
        switch (number)
        {
            case 1:
                xOffset = -2*64;
                yOffset = height/2 - 100;
                break;
            case 2:
                xOffset = -64;
                yOffset = height/2 - 100;
                break;
            case 3:
                xOffset = 0;
                yOffset = height/2 - 100;
                break;
            case 4:
                xOffset = 64;
                yOffset = height/2 - 100;
                break;
            case 5:
                xOffset = 2*64;
                yOffset = height/2 - 100;
                break;
            case 6:
                xOffset = -32;
                yOffset = height - 150;
                break;
            case 7:
                xOffset = 32;
                yOffset = height - 150;
                break;
            case 8:
                xOffset = -32;
                yOffset = 0;
                break;
            case 9:
                xOffset = 32;
                yOffset = 0;
                break;
            default:
                //throw new IllegalArgumentException("Invalid card number: " + number);
                xOffset = -300 + (number * 30); // space out cards horizontally
                yOffset = height - 150;         // player’s row
                break;
        }

        ImageView cardImageView = getCardImageView(card);
        cardImageView.setTranslateX(xOffset);
        cardImageView.setTranslateY(yOffset);
        table.getChildren().add(cardImageView);
    }

    private void addMenuItem(Menu menu, String name, Runnable action)
    {
        MenuItem menuItem = new MenuItem(name);
        menuItem.setOnAction(event -> action.run());
        menu.getItems().add(menuItem);
    }

    private void addKeyHandler()
    {
        root.setOnKeyPressed(event -> {
            System.out.println("Key pressed: " + event.getCode());
            switch (event.getCode())
            {
                // check for the key input
                case ESCAPE:
                    // remove focus from the textfields by giving it to the root VBox
                    root.requestFocus();
                    System.out.println("You pressed ESC key");
                    break;
                case ENTER:
                    System.out.println("You pressed ENTER key");
                    break;
                default:
                    System.out.println("you typed key: " + event.getCode());
                    break;
                
            }
        });
    }

      // === START OF BLACKJACK METHODS ===
      // setupBlackjackUI(), startNewGame(), hit(), stand(), calculateScore(), clearDealerSecondCard()

/**
 * Adds the Hit, Stand, and New Game buttons to the UI and sets their behavior.
 */
private void setupBlackjackUI() {
    // Add control buttons below the table
    root.getChildren().addAll(moneyLabel, controlButtons, bettingControls, resultLabel, restartButton);
    ;

    // Initially disable Hit and Stand until game starts
    hitButton.setDisable(true);
    standButton.setDisable(true);

// Bet placement logic
// Handle placing a bet
placeBetButton.setOnAction(new EventHandler<ActionEvent>() {
    @Override
    public void handle(ActionEvent event) {
        try {
            currentBet = Integer.parseInt(betInput.getText());
            if (currentBet <= 0 || currentBet > playerMoney) {
                resultLabel.setText("Invalid bet amount.");
            } else {
                resultLabel.setText("Bet placed: $" + currentBet);
                placeBetButton.setDisable(true);
                betInput.setDisable(true);
                startNewGame(); // start game after placing a valid bet
            }
        } catch (NumberFormatException ex) {
            resultLabel.setText("Please enter a valid number.");
        }
    }
});

// Handle restart game logic
restartButton.setOnAction(new EventHandler<ActionEvent>() {
    @Override
    public void handle(ActionEvent event) {
        playerMoney = 100;
        currentBet = 0;
        moneyLabel.setText("Money: $100");
        resultLabel.setText("Game restarted.");
        betInput.setDisable(false);
        placeBetButton.setDisable(false);
        betInput.clear();
        clearTable();
        hitButton.setDisable(true);
        standButton.setDisable(true);
    }
});

    // Make sure Hit and Stand buttons work
hitButton.setOnAction(new EventHandler<ActionEvent>() {
    @Override
    public void handle(ActionEvent event) {
        hit();
    }
});

standButton.setOnAction(new EventHandler<ActionEvent>() {
    @Override
    public void handle(ActionEvent event) {
        stand();
    }
});

};


    


/**
 * Starts a new round of Blackjack by shuffling the deck, dealing cards, and showing the initial state.
 */
private void startNewGame() {
    clearTable(); // reuse existing method to clear the board
    playerHand.clear();
    dealerHand.clear();
    deck = new Deck();
    deck.shuffle();
    resultLabel.setText(""); // Clear old message


    // Deal two cards each to player and dealer
    playerHand.add(deck.draw());
    dealerHand.add(deck.draw());
    playerHand.add(deck.draw());
    dealerHand.add(deck.draw());

    // Place player cards on screen (slots 6 and 7)
    placeCard(playerHand.get(0), 6);
    placeCard(playerHand.get(1), 7);

    // Place dealer's first card and a hidden second card (slots 8 and 9)
    placeCard(dealerHand.get(0), 8);
    placeCard(null, 9); // this shows the card back

    // Enable gameplay buttons
    hitButton.setDisable(false);
    standButton.setDisable(false);
}

/**
 * Adds one card to the player's hand and checks if they busted.
 */
private void hit() {
    Card card = deck.draw();
    playerHand.add(card);

    // Slot 6 and 7 are used, so we start new cards from slot 10
    int slot = 10 + playerHand.size(); 
    placeCard(card, slot);

    if (calculateScore(playerHand) > 21) {
        resultLabel.setText("💥 You Busted! Dealer wins.");
        playerMoney -= currentBet;
        moneyLabel.setText("Money: $" + playerMoney);

        hitButton.setDisable(true);
        standButton.setDisable(true);
        placeBetButton.setDisable(false);
        betInput.setDisable(false);
        betInput.clear();
    
        }
    }
    
    
    /**
 * Finishes the game: dealer reveals cards, draws until 17, and winner is declared.
 */
private void stand() {

        // Remove the back of card and show dealer’s second card
        clearDealerSecondCard();
        placeCard(dealerHand.get(1), 9);

        

    
        // Dealer draws until score is 17 or more
        while (calculateScore(dealerHand) < 17) {
            Card card = deck.draw();
            dealerHand.add(card);
            int slot = 20 + dealerHand.size();
            placeCard(card, slot);
        }
        
        // ✅ after dealer finishes, show result
        int playerScore = calculateScore(playerHand);
        int dealerScore = calculateScore(dealerHand);
        
        String resultText;
        if (dealerScore > 21 || playerScore > dealerScore) {
            resultText = "🎉 You Win!";
            playerMoney += currentBet;
        } else if (playerScore == dealerScore) {
            resultText = "🤝 It's a Tie!";
        } else {
            resultText = "💀 Dealer Wins!";
            playerMoney -= currentBet;
        }
        
        resultLabel.setText(resultText + " — Place a new bet or restart to play again.");
        moneyLabel.setText("Money: $" + playerMoney);
        placeBetButton.setDisable(false);
        betInput.setDisable(false);
        betInput.clear();
        hitButton.setDisable(true);
        standButton.setDisable(true);        
    
}

/**
 * Removes the back image used for dealer’s hidden card.
 */
private void clearDealerSecondCard() {
    table.getChildren().removeIf(node ->
        node instanceof ImageView &&
        ((ImageView) node).getImage().getUrl().contains("Back.png")
    );
}

/**
 * Calculates the total score of a hand, counting Aces as 11 or 1 based on situation.
 */
private int calculateScore(List<Card> hand) {
    int score = 0;
    int aceCount = 0;

    for (Card card : hand) {
        int value = card.getValue(); // Should return 1–10
        if (value == 1) {
            value = 11;
            aceCount++;
        }
        score += value;
    }

    // Adjust Ace from 11 to 1 if necessary to avoid busting
    while (score > 21 && aceCount > 0) {
        score -= 10;
        aceCount--;
    }

    return score;
}




// === END OF BLACKJACK METHODS ===

   
    public static void main(String[] args) 
    {
        launch(args);
    }
}
